void load_board(const char* filename, char board[9][9]);
void display_board(const char board[9][9]);
bool is_complete(const char board[9][9]);
bool make_move(const char* position, char digit, char board[9][9]);
bool save_board(const char* filename, const char board[9][9]);
bool column_check(const char* position, char digit, const char board[9][9]);
bool column_check(int column, char digit, const char board[9][9]);
bool row_check(const char* position, char digit, const char board[9][9]);
bool row_check(int row, char digit, const char board[9][9]);
bool block_check(const char* position, char digit, const char board[9][9]);
bool block_check(int row, int column, char digit, const char board[9][9]);
bool all_checks(const char* position, char digit, const char board[9][9]);
bool all_checks(int row, int column, char digit, const char board[9][9]);
bool solve_board_simple(char board[9][9]);
bool solve_board(char board[9][9]);
bool block_duplicates_tool(char board[9][9]);
bool column_duplicates_tool(char board[9][9]);
bool row_duplicates_tool(char board[9][9]);
bool use_all_tools(char board[9][9]);
void find_first_empty_box(int &row, int &column, const char board[9][9]);
void first_valid_digit(int row, int column, char &starting_digit, char board[9][9]);
void make_board_copy(const char board[9][9], char board_copy[9][9]);
